"""Shared utilities for code generation — header comment, naming, defaults,
import formatters.

**Zero-regex** — type pattern detection is delegated to the Lark-based
:mod:`._type_grammar` parser."""

import ast
import datetime
import hashlib
import re

from importlib.metadata import version as _pkg_version

from lark import LarkError

from ._type_grammar import parse_type


_PKG_VERSION: str = _pkg_version("zros2")


# ═══════════════════════════════════════════════════════════════════════════
# Header comment
# ═══════════════════════════════════════════════════════════════════════════


def _generated_metadata_stmts(source: str | None = None) -> list[ast.stmt]:
    """Return module-level assignment AST nodes for generated-file metadata.

    Every generated module should carry:

    * ``__generated__ = True`` — indicates the file is machine-generated.
    * ``__generator__ = "zros2-gen vX.Y.Z"`` — identifies the generator.
    * ``__source__ = "..."`` — the original ROS 2 IDL source file (omitted
      when ``source`` is ``None``, e.g. for ``__init__.py`` aggregations).
    """
    stmts: list[ast.stmt] = []
    stmts.append(ast.Assign(
        targets=[ast.Name(id="__generated__")],
        value=ast.Constant(value=True),
    ))
    stmts.append(ast.Assign(
        targets=[ast.Name(id="__generator__")],
        value=ast.Constant(value=f"zros2-gen v{_PKG_VERSION}"),
    ))
    if source is not None:
        stmts.append(ast.Assign(
            targets=[ast.Name(id="__source__")],
            value=ast.Constant(value=source),
        ))
    return stmts


def _header_comment(content: str = "", distro: str = "") -> str:
    """Return a "do not modify" header with timestamp and content SHA1.

    The hash is computed from *content* (everything after the header block).
    If *content* is empty the hash line is omitted (e.g. for the registry
    module which is built once at module load time).
    """
    ts = datetime.datetime.now(datetime.timezone.utc).isoformat(
        timespec="seconds"
    )
    lines = [
        f"# This file is auto-generated by zros2-gen v{_PKG_VERSION}. DO NOT MODIFY.",
    ]
    if content:
        sha = hashlib.sha1(content.encode("utf-8")).hexdigest()
        lines.append(f"# SHA1: {sha}")
    if distro:
        lines.append(f"# ROS 2 distro: {distro}")
    lines.append(f"# Generated at: {ts}")
    lines.append("")
    return "\n".join(lines) + "\n"


# ═══════════════════════════════════════════════════════════════════════════
# Naming
# ═══════════════════════════════════════════════════════════════════════════

def _to_snake_case(name: str) -> str:
    """Convert PascalCase to snake\\_case, preserving existing underscores."""
    parts = name.split("_")
    converted: list[str] = []
    for part in parts:
        s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", part)
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
        converted.append(s.lower())
    return "_".join(converted)


# ═══════════════════════════════════════════════════════════════════════════
# Default value expressions
# ═══════════════════════════════════════════════════════════════════════════

def _default_expr(type_str: str) -> str:
    """Return a Python default-value expression for a ROS 2 type, or empty.

    Uses the Lark type parser to determine the correct default based on
    the type's structure.
    """
    try:
        info = parse_type(type_str)
    except LarkError:
        return "None"

    base = info.base_name

    # ── Arrays / sequences ────────────────────────────────────────────
    if info.kind in ("unbounded", "unbounded_sequence") and base == "uint8":
        return "()"
    if info.kind in ("unbounded", "unbounded_sequence"):
        return "()"
    if info.kind == "fixed" and base == "uint8" and info.array_size:
        return f"(0,) * {info.array_size}"
    if info.kind in ("fixed", "bounded", "bounded_sequence"):
        return "()"

    # ── Bounded string ────────────────────────────────────────────────
    if info.is_bounded_string:
        return '""'

    # ── Scalars ───────────────────────────────────────────────────────
    if base in ("string", "wstring"):
        return '""'
    if base == "bool":
        return "False"
    if base in ("int8", "uint8", "int16", "uint16", "int32", "uint32",
                 "int64", "uint64", "byte", "char"):
        return "0"
    if base in ("float32", "float64"):
        return "0.0"
    if base in ("time", "duration"):
        return "None"

    return "None"


# ═══════════════════════════════════════════════════════════════════════════
# Import formatters
# ═══════════════════════════════════════════════════════════════════════════

def _format_pycdr2_imports(import_names: frozenset[str]) -> str:
    """Format the import statement for pycdr2.types."""
    if not import_names:
        return ""

    names = sorted(import_names)
    if len(names) <= 4:
        joined = ", ".join(names)
        return f"from pycdr2.types import {joined}"

    indent = " " * 4
    items = ",\n".join(f"{indent}{n}" for n in names)
    return f"from pycdr2.types import (\n{items},\n)"


def _format_external_imports(imports: list[str]) -> str:
    """Format external (cross-package) import statements."""
    if not imports:
        return ""
    return "\n".join(sorted(set(imports)))
